// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwU-jYf0K1_x74Pgx7H-VE37dhnka5Ue4',
    appId: '1:1044272843105:web:0cfec00cde38512cef9d20',
    messagingSenderId: '1044272843105',
    projectId: 'signin-29b67',
    authDomain: 'signin-29b67.firebaseapp.com',
    storageBucket: 'signin-29b67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYDUwYhOTCEIGsq--JvOtzgVIV8WIQoRs',
    appId: '1:1044272843105:android:4006cf93649dcb7def9d20',
    messagingSenderId: '1044272843105',
    projectId: 'signin-29b67',
    storageBucket: 'signin-29b67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwoXp0CEMK6y8Iet2R6S-8rRa1HUSZLjI',
    appId: '1:1044272843105:ios:3ff6c35a46a46b66ef9d20',
    messagingSenderId: '1044272843105',
    projectId: 'signin-29b67',
    storageBucket: 'signin-29b67.appspot.com',
    iosBundleId: 'com.example.plantproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwoXp0CEMK6y8Iet2R6S-8rRa1HUSZLjI',
    appId: '1:1044272843105:ios:3ff6c35a46a46b66ef9d20',
    messagingSenderId: '1044272843105',
    projectId: 'signin-29b67',
    storageBucket: 'signin-29b67.appspot.com',
    iosBundleId: 'com.example.plantproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwU-jYf0K1_x74Pgx7H-VE37dhnka5Ue4',
    appId: '1:1044272843105:web:9cf3ef7cbb4d4b22ef9d20',
    messagingSenderId: '1044272843105',
    projectId: 'signin-29b67',
    authDomain: 'signin-29b67.firebaseapp.com',
    storageBucket: 'signin-29b67.appspot.com',
  );
}
